@startuml
'https://plantuml.com/class-diagram

package Anki {
    class Collection
    class MediaManager
}

package NoteSize {
    together {
        class SizeButtonHooks
        class SizeColumnHooks
    }
    class SizeButtonFormatter
    class SizeCalculator
    class SizeFormatter
    class ItemIdCache
    class Init
}

Init --> SizeColumnHooks
Init --> SizeButtonHooks


SizeButtonFormatter --> ItemIdCache

SizeButtonHooks --> SizeButtonFormatter

SizeCalculator --> MediaManager

SizeColumnHooks --> Collection
SizeColumnHooks --> ItemIdCache

ItemIdCache --> Collection
ItemIdCache --> SizeCalculator
ItemIdCache --> SizeFormatter


@enduml