name: Execute unit-tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1 xvfb libxkbcommon-x11-0 libnss3 libxcomposite1 libxdamage1 libxrandr-dev libxtst6 libxi6 libasound2
          pip install --root-user-action=ignore --upgrade pip tox
      - name: Tox
        run: tox
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}